name: DiscordBridge
version: '1.1.2'
main: net.msstore.discordbridge.DiscordBridgePlugin
api-version: '26.2'
author: micr0softstore
description: a simple bukkit plugin for maaging server over dicord and having a bridge of miecraft chat in discord.


commands:
  db:
    description: Manage the DiscordBridge whitelist.
    usage: "/<command> console whitelist|unwhitelist <discord_user_id>"

permissions:
  dcbridge.whitelist:
    description: Allows whitelisting a Discord user ID to run console commands.
    default: op
  dcbridge.unwhitelist:
    description: Allows removing a Discord user ID from the whitelist.
    default: op
